# Generated by Django 6.0 on 2026-01-03 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_attendance_present_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='sport_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
