# Generated by Django 6.0 on 2026-01-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_member_membership_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='assurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date')},
        ),
    ]
